ARG VERSION_ID=focal
FROM arm64v8/ubuntu:${VERSION_ID} as stageforcopy
ARG VERSION_ID
FROM ubuntu:${VERSION_ID} as base
SHELL ["/bin/bash","-c"]
RUN echo "UTC" > /etc/timezone
RUN set -ex \
    && sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt install -y apt-utils \
    && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
              build-essential \
              bc \
              bison \
              binfmt-support \
              ca-certificates \
              ccache \
              cdbs \
              checkinstall \
              cmake \
              cpio \
              curl \
              debhelper \
              devscripts \
              distcc \
              dkms \
              dosfstools \
              dpkg-dev \
              e2fsprogs \
              equivs \
              fakeroot \
              flex \
              gawk \
              gcc-9 \
              cpp-9 \
              g++-9 \
              git \
              kernel-package \
              kpartx \
              libgpm2 \
              lsof \
              lz4 \
              libc6-arm64-cross \
              libelf-dev \
              libncurses-dev \
              libssl-dev \
              libxdelta2 \
              libxml2-utils \
              libpython3.8 \
              moreutils \
              ncurses-dev \
              patch \
              patchelf \
              piuparts \
              pkg-config \
              psmisc \
              pv \
              qemu-user-static \
              rsync \
              sbuild \
              sudo \
              tzdata \
              ubuntu-dev-tools \
              u-boot-tools \
              vim \
              vim-common \
              vim-runtime \
              wget \
              xdelta3 \
              xxd \
              xz-utils \
              gcc-aarch64-linux-gnu \
              cpp-aarch64-linux-gnu \
              g++-aarch64-linux-gnu \
              gcc-9-aarch64-linux-gnu \
              cpp-9-aarch64-linux-gnu \
              g++-9-aarch64-linux-gnu \
              gcc-9-aarch64-linux-gnu-base \
              libgcc-9-dev-arm64-cross \
              libstdc++-9-dev-arm64-cross \
              libc6-arm64-cross \
    && ln -sf /usr/aarch64-linux-gnu/lib \
    /lib/aarch64-linux-gnu \
    && ln -sf /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 \
    /lib/ld-linux-aarch64.so.1 \
    && DEBIAN_FRONTEND=noninteractive apt-get build-dep -y linux-image-generic \
    && DEBIAN_FRONTEND=noninteractive apt upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt dist-upgrade -y \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 10 \
    && update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-9 10 \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*
#COPY --from=stageforcopy /etc/apt/sources.list /etc/apt/sources.list.d/arm64.list
#RUN [[ ! $(uname -m) = aarch64 ]] \
#    && (sed -i 's/deb http/deb [arch=arm64] http/' \
#    /etc/apt/sources.list.d/arm64.list \
#    && sed -i 's/deb-src http/deb-src [arch=arm64] http/' \
#    /etc/apt/sources.list.d/arm64.list  \
#    && ln -sf /usr/aarch64-linux-gnu/lib \
#    /lib/aarch64-linux-gnu \
#    && ln -sf /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 \
#    /lib/ld-linux-aarch64.so.1 \
#    && dpkg --add-architecture arm64 \
#    && ( apt update || true )\
#    && apt install -y libssl-dev:arm64 -qq \
#    && apt-get clean && rm -rf /tmp/* /var/tmp/*)
