FROM arm64v8/ubuntu:19.04
RUN mkdir /arm64 && set -ex \
    && sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y \
    			bash-static \
    			libncurses-dev \
    			flex \
    			bison \
    			libssl-dev \
    			dkms \
    			libelf-dev \
    			qemu-user-static \
    			libc6-amd64-cross \
    && apt-get build-dep -y linux-image-generic \
    && apt-get install -y build-essential autoconf automake \
    libtool gawk alien fakeroot ksh \
    && apt-get install -y zlib1g-dev uuid-dev libattr1-dev libblkid-dev \
    libselinux-dev libudev-dev \
    && apt-get install -y libacl1-dev libaio-dev libdevmapper-dev \
    && apt-get install -y python3 python3-dev python3-setuptools python3-cffi \
    && apt-get upgrade -y \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*

FROM ubuntu:latest
COPY --from=0 . arm64_chroot/
RUN set -ex \
    && sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
               apt-transport-https \
               build-essential \
               bc \
               bison \
               binfmt-support \
               ca-certificates \
               ccache \
               cdbs \
               cmake \
               cpio \
               curl \
               devscripts \
               dkms \
               dosfstools \
               dpkg-dev \
               e2fsprogs \
               equivs \
               fakeroot \
               flex \
               gawk \
               git \
               kernel-package \
               kpartx \
               libgpm2 \
               lsof \
               liblz4-tool \
               libc6-arm64-cross \
               libelf-dev \
               libncurses-dev \
               libssl-dev \
               libxdelta2 \
               libpython3.7 \
               ncurses-dev \
               patch \
               psmisc \
               pv \
               qemu-user-static \
               rsync \
               sudo \
               u-boot-tools \
               vim \
               vim-common \
               vim-runtime \
               wget \
               xdelta3 \
               xxd \
               xz-utils \         
    && apt-get build-dep -y linux-image-raspi2 \
    && apt-get build-dep -y linux-image-generic \
    && apt-get upgrade -y \
RUN ["/bin/bash", "-c", "[[ ! $(uname -m) = aarch64 ]] && (apt-get install -y --no-install-recommends gcc-aarch64-linux-gnu \
               cpp-aarch64-linux-gnu \
               g++-aarch64-linux-gnu \
                || true )"]
RUN set -ex && apt-get clean && rm -rf /tmp/* /var/tmp/*
RUN set -ex && cp /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 /lib/  && cp -r /usr/aarch64-linux-gnu/lib/* /usr/lib/aarch64-linux-gnu/ && cp -r /arm64_chroot/usr/lib/aarch64-linux-gnu/* /usr/lib/aarch64-linux-gnu/ && echo "/usr/lib/aarch64-linux-gnu" >> /etc/ld.so.conf.d/aarch64-linux-gnu.conf
