ARG VERSION_ID=bionic
FROM arm64v8/ubuntu:${VERSION_ID} as stageforcopy
ARG VERSION_ID
FROM ubuntu:${VERSION_ID} as base
SHELL ["/bin/bash","-c"]
RUN set -ex \
    && sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
               apt-transport-https \
               build-essential \
               bc \
               bison \
               binfmt-support \
               ca-certificates \
               ccache \
               cdbs \
               checkinstall \
               cmake \
               cpio \
               curl \
               devscripts \
               dkms \
               dosfstools \
               dpkg-dev \
               e2fsprogs \
               equivs \
               fakeroot \
               flex \
               gawk \
               gcc-8 \
               cpp-8 \
               g++-8 \
               git \
               kernel-package \
               kpartx \
               libgpm2 \
               lsof \
               liblz4-tool \
               libc6-arm64-cross \
               libelf-dev \
               libncurses-dev \
               libssl-dev \
               libxdelta2 \
               libpython3.7 \
               moreutils \
               ncurses-dev \
               patch \
               pkg-config \
               psmisc \
               pv \
               qemu-user-static \
               rsync \
               sudo \
               u-boot-tools \
               vim \
               vim-common \
               vim-runtime \
               wget \
               xdelta3 \
               xxd \
               xz-utils \         
    && apt-get build-dep -y linux-image-raspi2 \
    && apt-get build-dep -y linux-image-generic \
    && apt-get upgrade -y \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*
COPY --from=stageforcopy /etc/apt/sources.list /etc/apt/sources.list.d/arm64.list
RUN [[ ! $(uname -m) = aarch64 ]] \
    && (sed -i 's/deb http/deb [arch=arm64] http/' \
    /etc/apt/sources.list.d/arm64.list \
    && sed -i 's/deb-src http/deb-src [arch=arm64] http/' \
    /etc/apt/sources.list.d/arm64.list \
    && dpkg --add-architecture arm64 \
    && ( apt update || true )\
    && apt install -y libssl-dev:arm64 -qq \
    && apt-get install -y --no-install-recommends \
                gcc-aarch64-linux-gnu \
                cpp-aarch64-linux-gnu \
                g++-aarch64-linux-gnu \
                gcc-8-aarch64-linux-gnu \
                cpp-8-aarch64-linux-gnu \
                g++-8-aarch64-linux-gnu \
                gcc-8-aarch64-linux-gnu-base \
                libgcc-8-dev-arm64-cross \
                libstdc++-8-dev-arm64-cross\
    && ln -sf /usr/aarch64-linux-gnu/lib \
    /lib/aarch64-linux-gnu \
    && ln -sf /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 \
    /lib/ld-linux-aarch64.so.1 \
    && sed -i 's/deb http/deb [arch=amd64] http/' /etc/apt/sources.list \
    && sed -i 's/deb-src http/deb-src [arch=amd64] http/' /etc/apt/sources.list \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 10 \
    && update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-8 10 \
    && apt-get clean && rm -rf /tmp/* /var/tmp/* )
RUN set -ex && apt-get clean && rm -rf /tmp/* /var/tmp/*
