FROM arm64v8/ubuntu:19.04
RUN set -ex \ 
    && sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y \
    			libncurses-dev \
    			flex \
    			bison \
    			openssl-dev \
    			libssl-dev \
    			dkms \
    			libelf-dev \
    			qemu-user-static \
    			libc6-amd64-cross \
    && apt-get build-dep -y linux-image-$(uname -r) \
    && apt-get install -y build-essential autoconf automake \
    libtool gawk alien fakeroot ksh \
    && apt-get install -y zlib1g-dev uuid-dev libattr1-dev libblkid-dev \
    libselinux-dev libudev-dev \
    && apt-get install -y libacl1-dev libaio-dev libdevmapper-dev \
    && apt-get install -y python3 python3-dev python3-setuptools python3-cffi \
    && apt-get upgrade -y \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*