FROM ubuntu:latest
RUN set -ex \
    && sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
               apt-transport-https \
               build-essential \
               bc \
               bison \
               binfmt-support \
               ca-certificates \
               ccache \
               cdbs \
               cmake \
               cpio \
               curl \
               devscripts \
               dkms \
               dosfstools \
               dpkg-dev \
               e2fsprogs \
               equivs \
               fakeroot \
               flex \
               gawk \
               gcc-8 \
               cpp-8 \
               g++-8 \
               git \
               kernel-package \
               kpartx \
               libgpm2 \
               lsof \
               liblz4-tool \
               libc6-arm64-cross \
               libelf-dev \
               libncurses-dev \
               libssl-dev \
               libxdelta2 \
               libpython3.7 \
               ncurses-dev \
               patch \
               psmisc \
               pv \
               qemu-user-static \
               rsync \
               sudo \
               u-boot-tools \
               vim \
               vim-common \
               vim-runtime \
               wget \
               xdelta3 \
               xxd \
               xz-utils \         
    && apt-get build-dep -y linux-image-raspi2 \
    && apt-get build-dep -y linux-image-generic \
    && apt-get upgrade -y \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*
RUN ["/bin/bash", "-c", "[[ ! $(uname -m) = aarch64 ]] \
    && (apt-get install -y --no-install-recommends \
                gcc-aarch64-linux-gnu \
                cpp-aarch64-linux-gnu \
                g++-aarch64-linux-gnu \
                gcc-8-aarch64-linux-gnu \
                cpp-8-aarch64-linux-gnu \
                g++-8-aarch64-linux-gnu \
                gcc-8-aarch64-linux-gnu-base \
                libgcc-8-dev-arm64-cross \
                libstdc++-8-dev-arm64-cross\
    && ln -sf /usr/aarch64-linux-gnu/lib /lib/aarch64-linux-gnu \
    && ln -sf /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 /lib/ld-linux-aarch64.so.1 \
    && (export arch=amd64 && sed -i 's/deb http/deb [arch=${arch}] http/' /etc/apt/sources.list) \
    && (export arch=amd64 && sed -i 's/deb-src http/deb-src [arch=${arch}] http/' /etc/apt/sources.list) \
    && VERSION_CODENAME=$(grep VERSION_CODENAME /etc/os-release | head -1 | awk -F '=' '{print $2}') && echo 'deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports ${VERSION_CODENAME} main restricted universe multiverse' >> /etc/apt/sources.list \
    && echo 'deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports ${VERSION_CODENAME}-updates main restricted universe multiverse' >> /etc/apt/sources.list \
    && dpkg --add-architecture arm64 \
    && apt update \
    && apt install -y libssl-dev:arm64 -qq \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 10 \
    && update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-8 10 \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*)"]
RUN set -ex && apt-get clean && rm -rf /tmp/* /var/tmp/*
